### ISSUE TITLE
Suggestion. Always checkbox should be toggleable.

### ISSUE THREAD

**Issue by JakobFangmeier** [RafalBuchner/StemPlow#3]
It would be cool, if when you assign the box for Always, the keybind would instead switch to a toggle for being on or off.

**Comment by RafalBuchner** [comment]
could you elaborate, or give some precise example how it would look like?

**Comment by JakobFangmeier** [comment]
Sure, so basically StemPlow already gives you the choice to assign a keybind to use it, displaying the distance whenever the key is pressed. 

When you select "Always" in the settings, the keybind becomes useless since it is displayed all the time anyways. So it might be nice to make the keybind a toggle is the always setting is selected.

You press the key and it stays on until you press the key again and it gets toggled off.

**Comment by RafalBuchner** [comment]
hmmm, interesting… :) 
I will add it to my todo list

**Comment by RafalBuchner** [comment]
@JakobFangmeier check out the latest update, I hope it is something that you were looking for :) And I hope it doesn't break :D

**Comment by RafalBuchner** [comment]
let me know if this is what you wanted, if not, then we can discuss implementing your idea better

**Comment by JakobFangmeier** [comment]
Perfect! Exactly what I wanted :) Thank you very much
